### ISSUE TITLE
The audio selection panel doesn't load!

### ISSUE THREAD

**Issue by aarkhipov40** [flixpressllc/ReactBasicTemplateEditor#42]
... when users don't have any custom audio

The custom audio panel doesn't show up likewise unless there are are more than 1 audio file available.

**Comment by happycollision** [comment]
I can actually look into this right now

**Comment by happycollision** [comment]
AWS has the fix. I am going to update master shortly, then you can pull, `npm run build` and put the resulting files on the server. But you will have to invaildate everyone's cache somehow. The new files will have a hash built in, if you'd like to start using that. If not, then you'll have to rename the 4 files to remove the hashes.

**Comment by happycollision** [comment]
Fixed with https://github.com/flixpressllc/ReactBasicTemplateEditor/commit/301c9fdaaaf33aa6a97320284bdee316695be14f
