### ISSUE TITLE
Properly Escaping & character

### ISSUE THREAD

**Issue by aarkhipov40** [flixpressllc/ReactBasicTemplateEditor#43]
Not sure if that's the front end thing, but the voice template doesn't render if there's a & char in textbox.   Are we escaping it for the XML properly?

**Comment by happycollision** [comment]
Probably not. I'll have a look tonight. I'll bet it is a quick fix.

**Comment by happycollision** [comment]
Actually, it looks fine... I submitted an order and here's the xml that was dumped on the page for just a text box with "text & speech" entered into it:

```xml
<?xml version="1.0" encoding="utf-16"?>
<OrderRequestOfTextOnlyRndTemplate xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ResolutionId>5</ResolutionId>
  <IsPreview>true</IsPreview>
  <ResolutionOptions>
    <ListItemViewModel>
      <Name>720p</Name>
      <Id>5</Id>
    </ListItemViewModel>
    <ListItemViewModel>
      <Name>1080p</Name>
      <Id>3</Id>
    </ListItemViewModel>
  </ResolutionOptions>
  <RenderedData>
    <Specs name="Specs" val="">
      <SpCx>
        <CSp name="Choose Voice and Language" val="CD|Choose Voice and Language|">
          <SpCx>
            <Sp name="Voice" val="Brian, (English-BR) Male"/>
          </SpCx>
        </CSp>
        <CSp name="Customize Look" val="CD|Customize Look|">
          <SpCx>
            <Sp name="Text Color" val="255.255.255"/>
            <Sp name="Background Color" val="0.200.250"/>
          </SpCx>
        </CSp>
        <CSp name="Customize Your Text" val="CD|Customize Your Text|">
          <SpCx>
            <Sp name="Main Text (one line per slide)" val="text & speech"/>
          </SpCx>
        </CSp>
      </SpCx>
    </Specs>
    <AudioInfo>
      <Length>0</Length>
      <Id>0</Id>
      <AudioType>NoAudio</AudioType>
      <Name/>
      <AudioUrl/>
    </AudioInfo>
  </RenderedData>
</OrderRequestOfTextOnlyRndTemplate>
```

**Comment by happycollision** [comment]
Looks like everything is getting properly escaped... here is an order I made:

```xml
<?xml version="1.0" encoding="utf-16"?>
<OrderRequestOfTextOnlyRndTemplate xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ResolutionId>5</ResolutionId>
  <IsPreview>true</IsPreview>
  <ResolutionOptions>
    <ListItemViewModel>
      <Name>720p</Name>
      <Id>5</Id>
    </ListItemViewModel>
    <ListItemViewModel>
      <Name>1080p</Name>
      <Id>3</Id>
    </ListItemViewModel>
  </ResolutionOptions>
  <RenderedData>
    <Specs name="Specs" val="">
      <SpCx>
        <CSp name="Choose Voice and Language" val="CD|Choose Voice and Language|">
          <SpCx>
            <Sp name="Voice" val="Brian, (English-BR) Male"/>
          </SpCx>
        </CSp>
        <CSp name="Customize Look" val="CD|Customize Look|">
          <SpCx>
            <Sp name="Text Color" val="255.255.255"/>
            <Sp name="Background Color" val="0.200.250"/>
          </SpCx>
        </CSp>
        <CSp name="Customize Your Text" val="CD|Customize Your Text|">
          <SpCx>
            <Sp name="Main Text (one line per slide)" val="text &amp; speech"/>
          </SpCx>
        </CSp>
      </SpCx>
    </Specs>
    <AudioInfo>
      <Length>0</Length>
      <Id>0</Id>
      <AudioType>NoAudio</AudioType>
      <Name/>
      <AudioUrl/>
    </AudioInfo>
  </RenderedData>
</OrderRequestOfTextOnlyRndTemplate>
```

**Comment by happycollision** [comment]
Not sure where the problem is.

**Comment by aarkhipov40** [comment]
It looks like an xml issue with amazon voice generating.  From: Don Denton Sent: Wed, Mar 8, 2017 12:11 AMTo: flixpressllc/ReactBasicTemplateEditor <ReactBasicTemplateEditor@noreply.github.com>CC: aarkhipov40 <andrey@flixpress.com>; Author <author@noreply.github.com>Subject: Re: [flixpressllc/ReactBasicTemplateEditor] Properly Escaping & character (#43)Looks like everything is getting properly escaped... here is an order I made:
<?xml version="1.0" encoding="utf-16"?>
<OrderRequestOfTextOnlyRndTemplate xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ResolutionId>5</ResolutionId>
  <IsPreview>true</IsPreview>
  <ResolutionOptions>
    <ListItemViewModel>
      <Name>720p</Name>
      <Id>5</Id>
    </ListItemViewModel>
    <ListItemViewModel>
      <Name>1080p</Name>
      <Id>3</Id>
    </ListItemViewModel>
  </ResolutionOptions>
  <RenderedData>
    <Specs name="Specs" val="">
      <SpCx>
        <CSp name="Choose Voice and Language" val="CD|Choose Voice and Language|">
          <SpCx>
            <Sp name="Voice" val="Brian, (English-BR) Male"/>
          </SpCx>
        </CSp>
        <CSp name="Customize Look" val="CD|Customize Look|">
          <SpCx>
            <Sp name="Text Color" val="255.255.255"/>
            <Sp name="Background Color" val="0.200.250"/>
          </SpCx>
        </CSp>
        <CSp name="Customize Your Text" val="CD|Customize Your Text|">
          <SpCx>
            <Sp name="Main Text (one line per slide)" val="text &amp; speech"/>
          </SpCx>
        </CSp>
      </SpCx>
    </Specs>
    <AudioInfo>
      <Length>0</Length>
      <Id>0</Id>
      <AudioType>NoAudio</AudioType>
      <Name/>
      <AudioUrl/>
    </AudioInfo>
  </RenderedData>
</OrderRequestOfTextOnlyRndTemplate>

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/flixpressllc/ReactBasicTemplateEditor","title":"flixpressllc/ReactBasicTemplateEditor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/flixpressllc/ReactBasicTemplateEditor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@happycollision in #43: Looks like everything is getting properly escaped... here is an order I made:\r\n\r\n```xml\r\n\u003c?xml version=\"1.0\" encoding=\"utf-16\"?\u003e\r\n\u003cOrderRequestOfTextOnlyRndTemplate xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\u003e\r\n  \u003cResolutionId\u003e5\u003c/ResolutionId\u003e\r\n  \u003cIsPreview\u003etrue\u003c/IsPreview\u003e\r\n  \u003cResolutionOptions\u003e\r\n    \u003cListItemViewModel\u003e\r\n      \u003cName\u003e720p\u003c/Name\u003e\r\n      \u003cId\u003e5\u003c/Id\u003e\r\n    \u003c/ListItemViewModel\u003e\r\n    \u003cListItemViewModel\u003e\r\n      \u003cName\u003e1080p\u003c/Name\u003e\r\n      \u003cId\u003e3\u003c/Id\u003e\r\n    \u003c/ListItemViewModel\u003e\r\n  \u003c/ResolutionOptions\u003e\r\n  \u003cRenderedData\u003e\r\n    \u003cSpecs name=\"Specs\" val=\"\"\u003e\r\n      \u003cSpCx\u003e\r\n        \u003cCSp name=\"Choose Voice and Language\" val=\"CD|Choose Voice and Language|\"\u003e\r\n          \u003cSpCx\u003e\r\n            \u003cSp name=\"Voice\" val=\"Brian, (English-BR) Male\"/\u003e\r\n          \u003c/SpCx\u003e\r\n        \u003c/CSp\u003e\r\n        \u003cCSp name=\"Customize Look\" val=\"CD|Customize Look|\"\u003e\r\n          \u003cSpCx\u003e\r\n            \u003cSp name=\"Text Color\" val=\"255.255.255\"/\u003e\r\n            \u003cSp name=\"Background Color\" val=\"0.200.250\"/\u003e\r\n          \u003c/SpCx\u003e\r\n        \u003c/CSp\u003e\r\n        \u003cCSp name=\"Customize Your Text\" val=\"CD|Customize Your Text|\"\u003e\r\n          \u003cSpCx\u003e\r\n            \u003cSp name=\"Main Text (one line per slide)\" val=\"text \u0026amp; speech\"/\u003e\r\n          \u003c/SpCx\u003e\r\n        \u003c/CSp\u003e\r\n      \u003c/SpCx\u003e\r\n    \u003c/Specs\u003e\r\n    \u003cAudioInfo\u003e\r\n      \u003cLength\u003e0\u003c/Length\u003e\r\n      \u003cId\u003e0\u003c/Id\u003e\r\n      \u003cAudioType\u003eNoAudio\u003c/AudioType\u003e\r\n      \u003cName/\u003e\r\n      \u003cAudioUrl/\u003e\r\n    \u003c/AudioInfo\u003e\r\n  \u003c/RenderedData\u003e\r\n\u003c/OrderRequestOfTextOnlyRndTemplate\u003e\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/flixpressllc/ReactBasicTemplateEditor/issues/43#issuecomment-284956425"}}}

**Comment by aarkhipov40** [comment]
Looks like it's an issue with Speech Markup that Amazon is using.

**Comment by happycollision** [comment]
Is this a back end issue then?

**Comment by aarkhipov40** [comment]
Yes.   I've removed the issue. Andrey ArkhipovCEO/CTOandrey@flixpress.com563-650-0598FlixPress LLC1910 E Kimberly Road Ste 102Davenport, IA 52807www.flixpress.comVisit Flixpress on Facebook Follow Flixpress on Twitter 


-------- Original Message --------
Subject: Re: [flixpressllc/ReactBasicTemplateEditor] Properly Escaping &
character (#43)
