### ISSUE TITLE
Extra XML tag

### ISSUE THREAD

**Issue by aarkhipov40** [flixpressllc/ReactBasicTemplateEditor#45]
Some of our users get an issue with incorrect formatting inserted into the serialized XML.

There's a tag that's being pushed at line 2 of XML that should not be there

<OrderRequestOfFSlidesRndTemplate xmlns='undefined'>

the compiler complains that it's not expected

Seems to be the issue with some instances of customizing an image-based templates.

**Comment by happycollision** [comment]
How can I reproduce the issue?
